### PR TITLE
Records import

### PR DESCRIPTION
**Pull request by ledsoft**
Resolves kbss-cvut/record-manager-ui#38.

The implementation besides record import also introduces a couple of proposed improvements:
- An application-wide messaging component (backed by a queue kept in Redux store). This would allow getting rid of all the `Alert`s that are displayed when events happen (e.g., a record is saved) in individual components. Instead, a single component that is always visible is used to communicate with the user.
- Promise tracking loader masks. These can be used to show loading mask during the evaluation of a promise - typically an async actions that waits for response from the server.

I added development notes for these proposed changes (`doc/components-libraries.md`). Their usage can be seen in this PR.

I also refactored all the checks for user's role being admin into a single function that is called from the components.

@LaChope I am tagging you just so you know about the additional changes I propose so that if they are approved by @blcham, you can use them as well and the newly added code is consistent in these areas.

### CODE REVIEW

**Review by blcham — CHANGES_REQUESTED** [review]
Code looks find, import works, I have just few suggestions to improve UX.

@ledsoft thank you for the proposed improvements, they are great!

**Comment by blcham** [comment]
- 1) Cannot see newest message:
image

- 2) Cannot see error message when import fails:
image

- 3) Cannot see imported records after import successfully finishes:
image

**Comment by ledsoft** [comment]
@blcham Ad i. and iv. - this is caused by a different alert shown by the components (`Records` in this case). These alerts are not part of the new messaging component I added. The messaging component works correctly, and it allows dismissing the messages (as you can see in iii.). I would consider refactoring all existing alerts to the new messaging component as a separate task.

I implemented the remaining feedback - show error message on failed import and reload records after import.

**Comment by blcham** [comment]
@ledsoft  I created issue as suggested -- https://github.com/kbss-cvut/record-manager-ui/issues/66.

Merging this PR and closing the ticket.

**Pull request merged**
